from __future__ import annotations

from platform_api.control_plane.schemas import NonQueryableSurface, PlatformResourceDescriptor


def _descriptor(
    resource_key: str,
    label: str,
    *,
    scope: str = "workspace",
    backing_source: str,
    queryable_fields: list[str],
    filterable_fields: list[str] | None = None,
    sortable_fields: list[str] | None = None,
    relationships: list[str] | None = None,
    default_limit: int = 20,
    freshness: str = "request-time",
    required_role: str = "member",
    redacted_fields: list[str] | None = None,
    available_actions: list[str] | None = None,
    canonical_ui: str | None = None,
    owner_module: str,
    resolver: str | None,
    tags: list[str],
    not_exposed_reason: str | None = None,
) -> PlatformResourceDescriptor:
    return PlatformResourceDescriptor(
        resource_key=resource_key,
        label=label,
        scope=scope,  # type: ignore[arg-type]
        backing_source=backing_source,
        queryable_fields=queryable_fields,
        filterable_fields=filterable_fields or [],
        sortable_fields=sortable_fields or [],
        relationships=relationships or [],
        default_limit=default_limit,
        freshness=freshness,
        required_role=required_role,  # type: ignore[arg-type]
        redacted_fields=redacted_fields or [],
        available_actions=available_actions or [],
        canonical_ui=canonical_ui,
        owner_module=owner_module,
        resolver=resolver,
        tags=tags,
        not_exposed_reason=not_exposed_reason,
    )


_CATALOG: tuple[PlatformResourceDescriptor, ...] = (
    _descriptor(
        "platform.overview",
        "Platform Overview",
        scope="workspace",
        backing_source="SQLAlchemy aggregate counts",
        queryable_fields=["workflows", "runs", "artifacts", "data_sources", "uploads", "approvals"],
        owner_module="platform_api.control_plane",
        resolver="overview",
        canonical_ui="/dashboard",
        tags=["platform", "system", "uygulama", "sistem", "overview", "durum", "all", "her sey", "tumu"],
    ),
    _descriptor(
        "identity.me",
        "Current User and Workspace",
        scope="user",
        backing_source="users, workspaces, workspace_memberships",
        queryable_fields=["user_id", "email", "workspace_id", "workspace_name", "workspace_role"],
        owner_module="platform_api.routes.me",
        resolver="identity",
        tags=["user", "identity", "workspace", "tenant", "kullanici", "calisma alani", "uyelik"],
    ),
    _descriptor(
        "configuration.settings",
        "Safe Platform Configuration",
        scope="workspace",
        backing_source="platform_api.core.config.settings",
        queryable_fields=[
            "deployment_profile",
            "auth_mode",
            "artifact_storage_backend",
            "chat_upload_max_mb",
            "csrf_enabled",
            "secret_policy",
        ],
        redacted_fields=["data_source_secret_key", "openai_api_key", "dev_auth_token"],
        owner_module="platform_api.core.config",
        resolver="configuration",
        canonical_ui="/settings",
        tags=["settings", "config", "configuration", "ayar", "policy", "security", "auth"],
    ),
    _descriptor(
        "data_sources",
        "Data Sources",
        scope="workspace",
        backing_source="data_sources",
        queryable_fields=["id", "name", "kind", "connection_uri", "metadata", "created_at", "updated_at"],
        filterable_fields=["kind", "name"],
        sortable_fields=["created_at", "updated_at", "name"],
        relationships=["workspace", "created_by_user"],
        redacted_fields=["connection_uri.password", "metadata.secret_ref", "metadata.password"],
        owner_module="platform_api.routes.data_sources",
        resolver="data_sources",
        available_actions=["data_sources.test"],
        canonical_ui="/data-sources",
        tags=["data source", "datasource", "sql", "sql server", "csv", "excel", "veri", "kaynak"],
    ),
    _descriptor(
        "chat.uploads",
        "Chat Uploads",
        scope="workspace",
        backing_source="chat_uploads",
        queryable_fields=["id", "session_id", "filename", "content_type", "size_bytes", "created_at"],
        filterable_fields=["filename", "content_type"],
        owner_module="platform_api.routes.chat",
        resolver="chat_uploads",
        canonical_ui="/ai-workspace",
        tags=["upload", "file", "csv", "excel", "chat", "dosya", "yukleme"],
    ),
    _descriptor(
        "workflows",
        "Workflow Specs",
        scope="workspace",
        backing_source="workflow_specs",
        queryable_fields=["id", "name", "version", "status", "validation_summary", "created_at", "updated_at"],
        filterable_fields=["name", "status"],
        sortable_fields=["created_at", "updated_at", "version"],
        relationships=["runs", "schedules", "artifacts"],
        owner_module="platform_api.routes.workflows",
        resolver="workflows",
        available_actions=["workflows.publish", "workflows.archive", "workflows.trigger"],
        canonical_ui="/workflows",
        tags=["workflow", "workflows", "pipeline", "graph", "schedule", "akis", "is akisi", "pipeline"],
    ),
    _descriptor(
        "workflow.schedules",
        "Workflow Schedules",
        scope="workspace",
        backing_source="workflow_specs schedule metadata; Prefect live deployment state adapter pending",
        queryable_fields=["workflow_spec_id", "workflow_name", "cron", "timezone", "enabled", "source"],
        filterable_fields=["workflow_spec_id", "enabled"],
        owner_module="platform_api.routes.workflows",
        resolver="workflow_schedules",
        available_actions=["schedules.pause", "schedules.resume"],
        canonical_ui="/workflows",
        tags=["schedule", "scheduler", "cron", "periodic", "periyodik", "zamanlama"],
    ),
    _descriptor(
        "runs",
        "Workflow Runs",
        scope="workspace",
        backing_source="workflow_runs",
        queryable_fields=["id", "flow_key", "workflow_spec_id", "status", "trigger_type", "started_at", "finished_at"],
        filterable_fields=["status", "workflow_spec_id", "flow_key"],
        sortable_fields=["created_at", "updated_at", "started_at", "finished_at"],
        relationships=["workflow", "nodes", "signals", "artifacts"],
        owner_module="platform_api.routes.runs",
        resolver="runs",
        available_actions=["runs.cancel", "runs.retry", "runs.resume"],
        canonical_ui="/runs",
        tags=["run", "runs", "execution", "job", "status", "calisma", "kosu", "gorev"],
    ),
    _descriptor(
        "run.nodes",
        "Run Node Executions",
        scope="workspace",
        backing_source="workflow_node_executions",
        queryable_fields=["id", "workflow_run_id", "node_id", "node_type", "status", "retry_count", "error"],
        filterable_fields=["workflow_run_id", "node_id", "status"],
        relationships=["run", "artifacts", "agent_traces"],
        owner_module="platform_api.services.workflow_node_execution_service",
        resolver="run_nodes",
        available_actions=["runs.nodes.retry"],
        canonical_ui="/runs",
        tags=["node", "step", "agent trace", "tool call", "trace", "adim", "agent"],
    ),
    _descriptor(
        "agent.traces",
        "Agent Execution Traces",
        scope="workspace",
        backing_source="agent_execution_traces",
        queryable_fields=[
            "id",
            "workflow_run_id",
            "workflow_node_execution_id",
            "node_id",
            "node_type",
            "attempt",
            "status",
            "duration_ms",
            "input_summary",
            "output_summary",
            "tool_calls",
            "artifact_ids",
            "token_usage",
            "cost_summary",
            "evaluation_summary",
            "version_metadata",
            "error_summary",
        ],
        filterable_fields=["workflow_run_id", "node_id", "node_type", "status"],
        sortable_fields=["started_at", "duration_ms", "created_at"],
        relationships=["run", "node", "artifacts"],
        redacted_fields=["raw_inputs", "raw_outputs", "private_reasoning", "secrets"],
        owner_module="platform_api.services.agent_execution_trace_service",
        resolver="agent_traces",
        canonical_ui="/agents",
        tags=["agent", "agents", "trace", "traces", "span", "tool call", "duration", "latency", "agent cockpit"],
    ),
    _descriptor(
        "run.signals",
        "Run Signals",
        scope="workspace",
        backing_source="workflow_signal_events",
        queryable_fields=["id", "workflow_run_id", "signal_type", "target_step", "note", "created_at"],
        filterable_fields=["workflow_run_id", "signal_type", "target_step"],
        owner_module="platform_api.routes.run_signals",
        resolver="run_signals",
        available_actions=["signals.emit"],
        canonical_ui="/monitor",
        tags=["signal", "event", "intervention", "pause", "resume", "sinyal", "olay"],
    ),
    _descriptor(
        "artifacts",
        "Artifacts",
        scope="workspace",
        backing_source="artifacts",
        queryable_fields=["id", "kind", "uri", "workflow_run_id", "produced_by_node_id", "parent_artifact_ids"],
        filterable_fields=["kind", "workflow_run_id", "produced_by_node_id"],
        relationships=["run", "node", "parent_artifacts", "child_artifacts"],
        redacted_fields=["uri.external_credentials"],
        owner_module="platform_api.routes.artifacts",
        resolver="artifacts",
        canonical_ui="/reports",
        tags=["artifact", "output", "report", "chart", "model", "lineage", "cikti", "rapor"],
    ),
    _descriptor(
        "approvals",
        "HITL Approvals",
        scope="workspace",
        backing_source="hitl_approvals",
        queryable_fields=["id", "workflow_run_id", "step_key", "status", "expires_at", "created_at"],
        filterable_fields=["status", "workflow_run_id", "step_key"],
        owner_module="platform_api.routes.hitl",
        resolver="approvals",
        canonical_ui="/approvals",
        tags=["approval", "hitl", "review", "onay", "insan"],
    ),
    _descriptor(
        "governance.audit",
        "Audit Log",
        scope="workspace",
        backing_source="audit_logs",
        queryable_fields=["id", "actor_user_id", "action", "workspace_id", "details", "created_at"],
        filterable_fields=["action", "actor_user_id"],
        required_role="workspace_admin",
        owner_module="platform_api.services.audit_service",
        resolver="audit",
        canonical_ui="/admin",
        tags=["audit", "governance", "rbac", "log", "denetim", "yetki"],
    ),
    _descriptor(
        "admin.ops",
        "Admin Operations",
        scope="admin",
        backing_source="outbox_dlq, scheduled_jobs, health/readiness metadata",
        queryable_fields=["queue", "dlq", "scheduler", "memory", "health"],
        required_role="tenant_admin",
        owner_module="platform_api.routes.admin",
        resolver="admin_ops",
        canonical_ui="/admin",
        available_actions=["dlq.replay"],
        tags=["admin", "ops", "health", "queue", "dlq", "scheduler", "monitoring", "operasyon"],
    ),
    _descriptor(
        "finops.cost",
        "FinOps and Cost Summary",
        scope="tenant",
        backing_source="artifacts, chat_uploads, workflow_runs, platform settings",
        queryable_fields=["artifacts", "uploads", "expired_artifacts", "workflow_runs", "retention", "recommendations"],
        required_role="tenant_admin",
        owner_module="platform_api.routes.finops",
        resolver="finops",
        canonical_ui="/admin",
        tags=["finops", "cost", "storage", "cleanup", "cache", "maliyet", "butce"],
    ),
    _descriptor(
        "agents.catalog",
        "Agent Catalog Metadata",
        scope="workspace",
        backing_source="future platform agent descriptor store",
        queryable_fields=["agent_key", "label", "capabilities", "status", "version"],
        owner_module="platform_api.control_plane",
        resolver=None,
        canonical_ui="/agents",
        tags=["agent", "agents", "catalog", "ajan"],
        not_exposed_reason=(
            "The control plane is independent from the DS/ML agent registry; "
            "a platform-owned agent descriptor resolver is required before querying this surface."
        ),
    ),
    _descriptor(
        "modelops",
        "ModelOps State",
        scope="workspace",
        backing_source="artifact-backed model inventory; future model registry and monitor store",
        queryable_fields=["registered_models", "monitor_snapshots", "versions", "deployments", "monitors", "drift", "retraining"],
        owner_module="platform_api.services.modelops_service",
        resolver="modelops_artifacts",
        canonical_ui="/modelops",
        tags=["model", "modelops", "drift", "monitor", "retrain", "ml"],
    ),
    _descriptor(
        "control_plane.adapters",
        "Control Plane Adapters",
        scope="system",
        backing_source="control-plane adapter contract metadata",
        queryable_fields=["adapter", "audience", "dependency_direction", "status", "notes"],
        owner_module="platform_api.control_plane",
        resolver="control_plane_adapters",
        canonical_ui="/ai-workspace",
        tags=["control plane", "chat", "cli", "mcp", "adapter", "integration", "tool"],
    ),
    _descriptor(
        "release.docs",
        "Release and Product Docs",
        scope="workspace",
        backing_source="tracked documentation files",
        queryable_fields=["path", "title", "status", "updated_at", "summary"],
        owner_module="docs",
        resolver="release_docs",
        canonical_ui=None,
        tags=["docs", "documentation", "release", "tasks", "roadmap", "dokuman", "task"],
    ),
)

_NON_QUERYABLE: tuple[NonQueryableSurface, ...] = (
    NonQueryableSurface(
        surface_key="secrets.raw_values",
        reason="Raw secrets are never queryable from chat, CLI, MCP, or control-plane APIs.",
        owner_module="platform_api.services.secret_store_service",
    ),
    NonQueryableSurface(
        surface_key="private_agent_reasoning",
        reason="Raw private reasoning is not persisted or exposed; only safe traces and outputs may become queryable.",
        owner_module="future agent observability",
    ),
    NonQueryableSurface(
        surface_key="destructive_workspace_actions",
        reason="Delete/rotate/destructive workspace actions are intentionally not exposed in the first action surface.",
        owner_module="platform_api.control_plane.actions",
    ),
)


def get_platform_catalog() -> list[PlatformResourceDescriptor]:
    return list(_CATALOG)


def get_non_queryable_surfaces() -> list[NonQueryableSurface]:
    return list(_NON_QUERYABLE)


def get_descriptor(resource_key: str) -> PlatformResourceDescriptor | None:
    for descriptor in _CATALOG:
        if descriptor.resource_key == resource_key:
            return descriptor
    return None


def catalog_resource_keys() -> set[str]:
    return {descriptor.resource_key for descriptor in _CATALOG}
