from __future__ import annotations

import importlib
import logging
from typing import Any

from ai_data_science_team.agent_registry import AgentRegistry

logger = logging.getLogger(__name__)


AGENT_BOOTSTRAP_SPECS: tuple[dict[str, Any], ...] = (
    {
        "name": "DataLoaderToolsAgent",
        "module": "ai_data_science_team.agents.data_loader_tools_agent",
        "class_name": "DataLoaderToolsAgent",
        "description": "Loads files into the workspace and normalizes raw input assets.",
        "capabilities": ["data_loading", "file_ingestion", "tabular_input"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "loader", "ingestion"],
    },
    {
        "name": "SQLDatabaseAgent",
        "module": "ai_data_science_team.agents.sql_database_agent",
        "class_name": "SQLDatabaseAgent",
        "description": "Queries relational sources and returns structured tabular results.",
        "capabilities": ["sql", "database_querying", "structured_data"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "sql", "database"],
    },
    {
        "name": "DataWranglingAgent",
        "module": "ai_data_science_team.agents.data_wrangling_agent",
        "class_name": "DataWranglingAgent",
        "description": "Reshapes datasets and prepares intermediate analytical tables.",
        "capabilities": ["data_wrangling", "reshape", "transformation"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "wrangling", "transformation"],
    },
    {
        "name": "DataCleaningAgent",
        "module": "ai_data_science_team.agents.data_cleaning_agent",
        "class_name": "DataCleaningAgent",
        "description": "Cleans datasets, handles missing values, and fixes schema issues.",
        "capabilities": ["data_cleaning", "imputation", "schema_fixing"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "cleaning", "quality"],
    },
    {
        "name": "EDAToolsAgent",
        "module": "ai_data_science_team.ds_agents.eda_tools_agent",
        "class_name": "EDAToolsAgent",
        "description": "Profiles datasets and produces exploratory analysis outputs.",
        "capabilities": ["eda", "profiling", "descriptive_stats"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "eda", "profiling"],
    },
    {
        "name": "DataVisualizationAgent",
        "module": "ai_data_science_team.agents.data_visualization_agent",
        "class_name": "DataVisualizationAgent",
        "description": "Builds plots, charts, and other data visualizations.",
        "capabilities": ["visualization", "charting", "plotting"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "visualization", "charts"],
    },
    {
        "name": "FeatureEngineeringAgent",
        "module": "ai_data_science_team.agents.feature_engineering_agent",
        "class_name": "FeatureEngineeringAgent",
        "description": "Creates model-ready features and derived analytical columns.",
        "capabilities": ["feature_engineering", "feature_selection", "transformation"],
        "cost_tier": "medium",
        "category": "ml",
        "tags": ["ml", "features", "preprocessing"],
    },
    {
        "name": "AnomalyDetectionAgent",
        "module": "ai_data_science_team.agents.anomaly_detection_agent",
        "class_name": "AnomalyDetectionAgent",
        "description": "Detects outliers, drift, and abnormal behavior in data or runs.",
        "capabilities": ["anomaly_detection", "outlier_detection", "monitoring"],
        "cost_tier": "medium",
        "category": "analysis",
        "tags": ["analysis", "anomaly", "monitoring"],
    },
    {
        "name": "DataQualityAgent",
        "module": "ai_data_science_team.agents.data_quality_agent",
        "class_name": "DataQualityAgent",
        "description": "Evaluates data quality, completeness, and validation issues.",
        "capabilities": ["data_quality", "validation", "profiling"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "quality", "validation"],
    },
    {
        "name": "APIConnectorAgent",
        "module": "ai_data_science_team.agents.api_connector_agent",
        "class_name": "APIConnectorAgent",
        "description": "Connects to HTTP APIs and normalizes external payloads.",
        "capabilities": ["api_ingestion", "http", "external_data"],
        "cost_tier": "medium",
        "category": "data",
        "tags": ["data", "api", "connector"],
    },
    {
        "name": "DocumentParserAgent",
        "module": "ai_data_science_team.agents.document_parser_agent",
        "class_name": "DocumentParserAgent",
        "description": "Extracts structured data from uploaded documents and text assets.",
        "capabilities": ["document_parsing", "ocr", "text_extraction"],
        "cost_tier": "medium",
        "category": "data",
        "tags": ["data", "documents", "parsing"],
    },
    {
        "name": "ModelServingAgent",
        "module": "ai_data_science_team.agents.model_serving_agent",
        "class_name": "ModelServingAgent",
        "description": "Packages model inference behavior for serving and prediction workflows.",
        "capabilities": ["model_serving", "inference", "deployment"],
        "cost_tier": "medium",
        "category": "ops",
        "tags": ["ops", "serving", "inference"],
    },
    {
        "name": "ModelMonitoringAgent",
        "module": "ai_data_science_team.agents.model_monitoring_agent",
        "class_name": "ModelMonitoringAgent",
        "description": "Monitors model quality, drift, and operational health signals.",
        "capabilities": ["model_monitoring", "drift_detection", "alerting"],
        "cost_tier": "medium",
        "category": "ops",
        "tags": ["ops", "monitoring", "drift"],
    },
    {
        "name": "ModelExplainabilityAgent",
        "module": "ai_data_science_team.agents.model_explainability_agent",
        "class_name": "ModelExplainabilityAgent",
        "description": "Generates explainability artifacts and feature-importance narratives.",
        "capabilities": ["explainability", "feature_importance", "shap"],
        "cost_tier": "medium",
        "category": "ops",
        "tags": ["ops", "explainability", "model"],
    },
    {
        "name": "ResultsSynthesizerAgent",
        "module": "ai_data_science_team.agents.strategic_agents",
        "class_name": "ResultsSynthesizerAgent",
        "description": "Synthesizes analytical outputs into concise result summaries.",
        "capabilities": ["results_synthesis", "summarization", "reporting"],
        "cost_tier": "low",
        "category": "strategy",
        "tags": ["strategy", "synthesis", "reporting"],
    },
    {
        "name": "ContextualKnowledgeAgent",
        "module": "ai_data_science_team.agents.strategic_agents",
        "class_name": "ContextualKnowledgeAgent",
        "description": "Adds business context and supporting knowledge to analytical findings.",
        "capabilities": ["contextual_knowledge", "retrieval", "business_context"],
        "cost_tier": "low",
        "category": "strategy",
        "tags": ["strategy", "context", "knowledge"],
    },
    {
        "name": "NarrativeAgent",
        "module": "ai_data_science_team.agents.strategic_agents",
        "class_name": "NarrativeAgent",
        "description": "Builds user-facing narratives and executive summaries from results.",
        "capabilities": ["narrative_generation", "summarization", "reporting"],
        "cost_tier": "low",
        "category": "strategy",
        "tags": ["strategy", "narrative", "reports"],
    },
    {
        "name": "RecommendationAgent",
        "module": "ai_data_science_team.agents.strategic_agents",
        "class_name": "RecommendationAgent",
        "description": "Turns workflow findings into recommendations and next actions.",
        "capabilities": ["recommendation", "decision_support", "prioritization"],
        "cost_tier": "low",
        "category": "strategy",
        "tags": ["strategy", "recommendation", "decision"],
    },
    {
        "name": "WorkflowPlannerAgent",
        "module": "ai_data_science_team.agents.workflow_planner_agent",
        "class_name": "WorkflowPlannerAgent",
        "description": "Plans candidate workflows before execution and review.",
        "capabilities": ["workflow_planning", "task_breakdown", "routing"],
        "cost_tier": "low",
        "category": "orchestration",
        "tags": ["orchestration", "planning", "workflow"],
    },
    {
        "name": "ApprovalGateAgent",
        "module": "ai_data_science_team.agents.hitl_agent",
        "class_name": "ApprovalGateAgent",
        "description": "Inserts human approval and review checkpoints into workflows.",
        "capabilities": ["approval", "human_in_the_loop", "governance"],
        "cost_tier": "low",
        "category": "human_in_the_loop",
        "tags": ["hitl", "approval", "governance"],
    },
    {
        "name": "OrchestratorAgent",
        "module": "ai_data_science_team.agents.orchestrator_agent",
        "class_name": "OrchestratorAgent",
        "description": "Coordinates dynamic workflow resolution and multi-step execution.",
        "capabilities": ["orchestration", "workflow_resolution", "multi_agent_execution"],
        "cost_tier": "medium",
        "category": "orchestration",
        "tags": ["orchestration", "runtime", "multi-agent"],
    },
    # ------------------------------------------------------------------
    # Experimentation & Analysis (A-series)
    # ------------------------------------------------------------------
    {
        "name": "ABTestingAgent",
        "module": "ai_data_science_team.agents.ab_testing_agent",
        "class_name": "ABTestingAgent",
        "description": "Designs and analyzes A/B experiments with statistical rigor.",
        "capabilities": ["ab_testing", "experiment_design", "statistical_analysis"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "experiments", "statistics"],
    },
    {
        "name": "PowerAnalysisAgent",
        "module": "ai_data_science_team.agents.power_analysis_agent",
        "class_name": "PowerAnalysisAgent",
        "description": "Computes sample size, MDE, and statistical power for experiment design.",
        "capabilities": ["power_analysis", "sample_size", "experiment_design"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "power", "statistics"],
    },
    {
        "name": "BayesianAnalysisAgent",
        "module": "ai_data_science_team.agents.bayesian_agent",
        "class_name": "BayesianAnalysisAgent",
        "description": "Performs Bayesian A/B analysis with posterior distributions and credible intervals.",
        "capabilities": ["bayesian", "posterior_analysis", "probabilistic_inference"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "bayesian", "statistics"],
    },
    {
        "name": "HypothesisTestingAgent",
        "module": "ai_data_science_team.agents.hypothesis_testing_agent",
        "class_name": "HypothesisTestingAgent",
        "description": "Applies parametric and non-parametric hypothesis tests to experimental data.",
        "capabilities": ["hypothesis_testing", "significance_testing", "statistical_tests"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "hypothesis", "statistics"],
    },
    {
        "name": "CausalInferenceAgent",
        "module": "ai_data_science_team.agents.causal_agent",
        "class_name": "CausalInferenceAgent",
        "description": "Estimates causal effects and performs did-lift analysis from observational data.",
        "capabilities": ["causal_inference", "treatment_effect", "did_analysis"],
        "cost_tier": "medium",
        "category": "analysis",
        "tags": ["analysis", "causal", "inference"],
    },
    # ------------------------------------------------------------------
    # Data Profiling, Ingestion & Quality (B-series)
    # ------------------------------------------------------------------
    {
        "name": "DataProfilingAgent",
        "module": "ai_data_science_team.agents.profiling_agent",
        "class_name": "DataProfilingAgent",
        "description": "Profiles datasets with Sweetviz and D-Tale for comprehensive exploratory analysis.",
        "capabilities": ["profiling", "exploratory_analysis", "data_summary"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "profiling", "eda"],
    },
    {
        "name": "SchemaInferenceAgent",
        "module": "ai_data_science_team.agents.schema_agent",
        "class_name": "SchemaInferenceAgent",
        "description": "Infers and validates schemas from tabular datasets.",
        "capabilities": ["schema_inference", "schema_validation", "data_types"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "schema", "validation"],
    },
    {
        "name": "PIIAnonymizationAgent",
        "module": "ai_data_science_team.agents.pii_agent",
        "class_name": "PIIAnonymizationAgent",
        "description": "Detects and redacts personally identifiable information in datasets.",
        "capabilities": ["pii_detection", "anonymization", "privacy"],
        "cost_tier": "medium",
        "category": "data",
        "tags": ["data", "pii", "privacy"],
    },
    {
        "name": "DataIngestionAgent",
        "module": "ai_data_science_team.agents.data_ingestion_agent",
        "class_name": "DataIngestionAgent",
        "description": "Ingests data from file uploads and external sources into the workspace.",
        "capabilities": ["data_ingestion", "file_upload", "external_data"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "ingestion", "upload"],
    },
    # ------------------------------------------------------------------
    # Insights & Reporting (C-series)
    # ------------------------------------------------------------------
    {
        "name": "InsightMiningAgent",
        "module": "ai_data_science_team.agents.insight_agent",
        "class_name": "InsightMiningAgent",
        "description": "Mines datasets for patterns, correlations, and actionable insights.",
        "capabilities": ["insight_mining", "pattern_discovery", "data_analysis"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "insights", "pattern"],
    },
    {
        "name": "DashboardComposerAgent",
        "module": "ai_data_science_team.agents.dashboard_agent",
        "class_name": "DashboardComposerAgent",
        "description": "Composes interactive dashboards from analytical outputs.",
        "capabilities": ["dashboard", "visualization", "reporting"],
        "cost_tier": "medium",
        "category": "analysis",
        "tags": ["analysis", "dashboard", "reporting"],
    },
    {
        "name": "KPIMetricsAgent",
        "module": "ai_data_science_team.agents.kpi_agent",
        "class_name": "KPIMetricsAgent",
        "description": "Defines, tracks, and reports on key performance indicators.",
        "capabilities": ["kpi", "metrics", "performance_tracking"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "kpi", "metrics"],
    },
    {
        "name": "RootCauseAnalysisAgent",
        "module": "ai_data_science_team.agents.rootcause_agent",
        "class_name": "RootCauseAnalysisAgent",
        "description": "Performs root-cause analysis on metric anomalies and data quality issues.",
        "capabilities": ["root_cause", "anomaly_investigation", "diagnostics"],
        "cost_tier": "medium",
        "category": "analysis",
        "tags": ["analysis", "root_cause", "diagnostics"],
    },
    {
        "name": "ReportGeneratorAgent",
        "module": "ai_data_science_team.agents.reports_agent",
        "class_name": "ReportGeneratorAgent",
        "description": "Generates structured report templates from analytical outputs.",
        "capabilities": ["report_generation", "templating", "documentation"],
        "cost_tier": "low",
        "category": "analysis",
        "tags": ["analysis", "reports", "documentation"],
    },
    # ------------------------------------------------------------------
    # Features & Balance (D-series)
    # ------------------------------------------------------------------
    {
        "name": "FeatureSelectionAgent",
        "module": "ai_data_science_team.agents.features_agent",
        "class_name": "FeatureSelectionAgent",
        "description": "Selects and engineers features for machine learning pipelines.",
        "capabilities": ["feature_selection", "feature_engineering", "ml_prep"],
        "cost_tier": "medium",
        "category": "ml",
        "tags": ["ml", "features", "selection"],
    },
    {
        "name": "FeatureStoreAgent",
        "module": "ai_data_science_team.agents.feature_store_agent",
        "class_name": "FeatureStoreAgent",
        "description": "Manages a centralized feature store for consistent ML training and serving.",
        "capabilities": ["feature_store", "feature_registry", "feature_serving"],
        "cost_tier": "medium",
        "category": "ml",
        "tags": ["ml", "feature_store", "registry"],
    },
    {
        "name": "DataBalancingAgent",
        "module": "ai_data_science_team.agents.balance_agent",
        "class_name": "DataBalancingAgent",
        "description": "Handles imbalanced datasets with sampling and weighting strategies.",
        "capabilities": ["imbalanced_data", "sampling", "class_balancing"],
        "cost_tier": "low",
        "category": "ml",
        "tags": ["ml", "balance", "sampling"],
    },
    # ------------------------------------------------------------------
    # ML Training (E-series)
    # ------------------------------------------------------------------
    {
        "name": "HPOAgent",
        "module": "ai_data_science_team.agents.hpo_agent",
        "class_name": "HPOAgent",
        "description": "Performs hyperparameter optimization across model types.",
        "capabilities": ["hpo", "hyperparameter_tuning", "optimization"],
        "cost_tier": "high",
        "category": "ml",
        "tags": ["ml", "hpo", "tuning"],
    },
    {
        "name": "DeepLearningAgent",
        "module": "ai_data_science_team.agents.deep_learning_agent",
        "class_name": "DeepLearningAgent",
        "description": "Builds and trains deep learning models for vision, text, and tabular data.",
        "capabilities": ["deep_learning", "neural_networks", "dl_training"],
        "cost_tier": "high",
        "category": "ml",
        "tags": ["ml", "deep_learning", "neural"],
    },
    {
        "name": "TimeSeriesForecastAgent",
        "module": "ai_data_science_team.agents.time_series_agent",
        "class_name": "TimeSeriesForecastAgent",
        "description": "Forecasts time-series data using statistical and ML methods.",
        "capabilities": ["time_series", "forecasting", "trend_analysis"],
        "cost_tier": "medium",
        "category": "ml",
        "tags": ["ml", "time_series", "forecast"],
    },
    {
        "name": "ClusteringAgent",
        "module": "ai_data_science_team.agents.clustering_agent",
        "class_name": "ClusteringAgent",
        "description": "Segments data using clustering algorithms with profile interpretation.",
        "capabilities": ["clustering", "segmentation", "unsupervised"],
        "cost_tier": "low",
        "category": "ml",
        "tags": ["ml", "clustering", "segmentation"],
    },
    # ------------------------------------------------------------------
    # ML Evaluation (F-series)
    # ------------------------------------------------------------------
    {
        "name": "EvaluationExtAgent",
        "module": "ai_data_science_team.agents.evaluation_ext_agent",
        "class_name": "EvaluationExtAgent",
        "description": "Extends model evaluation with advanced metrics and comparison reports.",
        "capabilities": ["model_evaluation", "metrics", "comparison"],
        "cost_tier": "low",
        "category": "ml",
        "tags": ["ml", "evaluation", "metrics"],
    },
    {
        "name": "ChampionChallengerAgent",
        "module": "ai_data_science_team.agents.champion_challenger_agent",
        "class_name": "ChampionChallengerAgent",
        "description": "Manages champion-challenger model comparisons and promotions.",
        "capabilities": ["champion_challenger", "model_comparison", "model_promotion"],
        "cost_tier": "low",
        "category": "ml",
        "tags": ["ml", "champion", "challenger"],
    },
    {
        "name": "FairnessAuditAgent",
        "module": "ai_data_science_team.agents.fairness_agent",
        "class_name": "FairnessAuditAgent",
        "description": "Audits model fairness across demographic and protected groups.",
        "capabilities": ["fairness_audit", "bias_detection", "model_fairness"],
        "cost_tier": "medium",
        "category": "ml",
        "tags": ["ml", "fairness", "bias"],
    },
    {
        "name": "ModelCardAgent",
        "module": "ai_data_science_team.agents.model_card_agent",
        "class_name": "ModelCardAgent",
        "description": "Generates model cards documenting model purpose, performance, and limitations.",
        "capabilities": ["model_card", "documentation", "governance"],
        "cost_tier": "low",
        "category": "ml",
        "tags": ["ml", "model_card", "documentation"],
    },
    {
        "name": "RobustnessTestAgent",
        "module": "ai_data_science_team.agents.robustness_agent",
        "class_name": "RobustnessTestAgent",
        "description": "Tests model robustness through perturbation and adversarial evaluation.",
        "capabilities": ["robustness_testing", "perturbation", "adversarial"],
        "cost_tier": "medium",
        "category": "ml",
        "tags": ["ml", "robustness", "testing"],
    },
    {
        "name": "LLMJudgeAgent",
        "module": "ai_data_science_team.agents.llm_judge_agent",
        "class_name": "LLMJudgeAgent",
        "description": "Evaluates LLM outputs using rubric-based and pairwise judging.",
        "capabilities": ["llm_evaluation", "judging", "rubric_scoring"],
        "cost_tier": "medium",
        "category": "ml",
        "tags": ["ml", "llm", "evaluation"],
    },
    # ------------------------------------------------------------------
    # ML Ops (G-series, excluding ModelServing above)
    # ------------------------------------------------------------------
    {
        "name": "DriftDetectionAgent",
        "module": "ai_data_science_team.agents.drift_agent",
        "class_name": "DriftDetectionAgent",
        "description": "Detects concept drift and data drift in production model inputs.",
        "capabilities": ["drift_detection", "concept_drift", "monitoring"],
        "cost_tier": "medium",
        "category": "ops",
        "tags": ["ops", "drift", "monitoring"],
    },
    {
        "name": "RetrainOrchestratorAgent",
        "module": "ai_data_science_team.agents.retrain_orchestrator_agent",
        "class_name": "RetrainOrchestratorAgent",
        "description": "Orchestrates automated model retraining pipelines triggered by drift.",
        "capabilities": ["retraining", "auto_ml", "pipeline_orchestration"],
        "cost_tier": "high",
        "category": "ops",
        "tags": ["ops", "retraining", "automation"],
    },
    {
        "name": "BatchScoringAgent",
        "module": "ai_data_science_team.agents.batch_scoring_agent",
        "class_name": "BatchScoringAgent",
        "description": "Runs batch inference on large datasets using deployed models.",
        "capabilities": ["batch_scoring", "bulk_inference", "scoring"],
        "cost_tier": "high",
        "category": "ops",
        "tags": ["ops", "batch", "scoring"],
    },
    {
        "name": "ModelPromotionAgent",
        "module": "ai_data_science_team.agents.promotion_agent",
        "class_name": "ModelPromotionAgent",
        "description": "Manages model registry promotion workflows across staging environments.",
        "capabilities": ["model_promotion", "registry", "staging"],
        "cost_tier": "low",
        "category": "ops",
        "tags": ["ops", "promotion", "registry"],
    },
    {
        "name": "AlertingAgent",
        "module": "ai_data_science_team.agents.alerting_agent",
        "class_name": "AlertingAgent",
        "description": "Configures and sends alerts for model and data pipeline events.",
        "capabilities": ["alerting", "notifications", "monitoring"],
        "cost_tier": "low",
        "category": "ops",
        "tags": ["ops", "alerting", "notifications"],
    },
    # ------------------------------------------------------------------
    # Data Connectors (H-series)
    # ------------------------------------------------------------------
    {
        "name": "SnowflakeSourceAgent",
        "module": "ai_data_science_team.agents.snowflake_agent",
        "class_name": "SnowflakeSourceAgent",
        "description": "Queries Snowflake data warehouses and returns structured results.",
        "capabilities": ["snowflake", "data_warehouse", "sql"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "snowflake", "sql"],
    },
    {
        "name": "BigQuerySourceAgent",
        "module": "ai_data_science_team.agents.bigquery_agent",
        "class_name": "BigQuerySourceAgent",
        "description": "Queries Google BigQuery and returns structured results.",
        "capabilities": ["bigquery", "gcp", "sql"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "bigquery", "gcp"],
    },
    {
        "name": "TableauSourceAgent",
        "module": "ai_data_science_team.agents.tableau_agent",
        "class_name": "TableauSourceAgent",
        "description": "Interacts with Tableau Server for dashboard and data source management.",
        "capabilities": ["tableau", "visualization", "bi"],
        "cost_tier": "medium",
        "category": "data",
        "tags": ["data", "tableau", "bi"],
    },
    {
        "name": "PowerBISourceAgent",
        "module": "ai_data_science_team.agents.powerbi_agent",
        "class_name": "PowerBISourceAgent",
        "description": "Interacts with Microsoft Power BI for dashboard and report management.",
        "capabilities": ["powerbi", "visualization", "bi"],
        "cost_tier": "medium",
        "category": "data",
        "tags": ["data", "powerbi", "bi"],
    },
    {
        "name": "SheetsSourceAgent",
        "module": "ai_data_science_team.agents.sheets_agent",
        "class_name": "SheetsSourceAgent",
        "description": "Reads and writes data from Google Sheets.",
        "capabilities": ["sheets", "google_workspace", "spreadsheet"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "sheets", "google"],
    },
    {
        "name": "ObjectStorageAgent",
        "module": "ai_data_science_team.agents.object_storage_agent",
        "class_name": "ObjectStorageAgent",
        "description": "Reads and writes artifacts from S3/GCS-compatible object storage.",
        "capabilities": ["object_storage", "s3", "gcs", "artifact_storage"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "storage", "s3"],
    },
    {
        "name": "RESTAPISourceAgent",
        "module": "ai_data_science_team.agents.rest_api_agent",
        "class_name": "RESTAPISourceAgent",
        "description": "Connects to REST APIs for data ingestion and external service integration.",
        "capabilities": ["rest_api", "http", "integration"],
        "cost_tier": "medium",
        "category": "data",
        "tags": ["data", "api", "rest"],
    },
    # ------------------------------------------------------------------
    # Governance & Discovery (I-series)
    # ------------------------------------------------------------------
    {
        "name": "DataCatalogAgent",
        "module": "ai_data_science_team.agents.catalog_agent",
        "class_name": "DataCatalogAgent",
        "description": "Manages a data catalog for discovering and governing datasets.",
        "capabilities": ["data_catalog", "discovery", "metadata"],
        "cost_tier": "low",
        "category": "governance",
        "tags": ["governance", "catalog", "discovery"],
    },
    {
        "name": "ExperimentTrackerAgent",
        "module": "ai_data_science_team.agents.leaderboard_agent",
        "class_name": "ExperimentTrackerAgent",
        "description": "Tracks experiment results and maintains model leaderboards.",
        "capabilities": ["leaderboard", "experiment_tracking", "comparison"],
        "cost_tier": "low",
        "category": "governance",
        "tags": ["governance", "leaderboard", "tracking"],
    },
    # ------------------------------------------------------------------
    # Investigation, Lineage & Governance (J-series)
    # ------------------------------------------------------------------
    {
        "name": "InvestigationAgent",
        "module": "ai_data_science_team.agents.investigation_agent",
        "class_name": "InvestigationAgent",
        "description": "Autonomous investigation of system behavior and data anomalies.",
        "capabilities": ["investigation", "debugging", "root_cause"],
        "cost_tier": "medium",
        "category": "governance",
        "tags": ["governance", "investigation", "debugging"],
    },
    {
        "name": "ResponsibleAIAgent",
        "module": "ai_data_science_team.agents.responsible_ai_agent",
        "class_name": "ResponsibleAIAgent",
        "description": "Ensures responsible AI practices including fairness and transparency.",
        "capabilities": ["responsible_ai", "ethics", "governance"],
        "cost_tier": "medium",
        "category": "governance",
        "tags": ["governance", "responsible", "ethics"],
    },
    {
        "name": "GovernanceAgent",
        "module": "ai_data_science_team.agents.governance_agent",
        "class_name": "GovernanceAgent",
        "description": "Enforces data and model governance policies across the platform.",
        "capabilities": ["governance", "policy", "compliance"],
        "cost_tier": "low",
        "category": "governance",
        "tags": ["governance", "policy", "compliance"],
    },
    {
        "name": "ShadowCanaryAgent",
        "module": "ai_data_science_team.agents.shadow_canary_agent",
        "class_name": "ShadowCanaryAgent",
        "description": "Manages shadow/canary deployments for safe model rollout.",
        "capabilities": ["shadow_deployment", "canary", "deployment_safety"],
        "cost_tier": "medium",
        "category": "ops",
        "tags": ["ops", "shadow", "canary"],
    },
    {
        "name": "LineageGraphAgent",
        "module": "ai_data_science_team.agents.lineage_agent",
        "class_name": "LineageGraphAgent",
        "description": "Tracks data and model lineage across the platform.",
        "capabilities": ["lineage", "provenance", "data_tracking"],
        "cost_tier": "low",
        "category": "governance",
        "tags": ["governance", "lineage", "tracking"],
    },
    {
        "name": "DataDiffAgent",
        "module": "ai_data_science_team.agents.data_diff_agent",
        "class_name": "DataDiffAgent",
        "description": "Compares datasets and identifies schema and content differences.",
        "capabilities": ["data_diff", "comparison", "schema_diff"],
        "cost_tier": "low",
        "category": "data",
        "tags": ["data", "diff", "comparison"],
    },
)


def _import_agent_class(module_path: str, class_name: str) -> type[Any]:
    module = importlib.import_module(module_path)
    return getattr(module, class_name)


def register_production_agent_catalog(*, clear_existing: bool = False) -> dict[str, Any]:
    """Register the production-safe agent catalog used by discovery and M22 rollout."""
    if clear_existing:
        AgentRegistry.clear()

    registered_names: list[str] = []
    skipped: dict[str, str] = {}

    for spec in AGENT_BOOTSTRAP_SPECS:
        name = str(spec["name"])
        try:
            agent_class = _import_agent_class(str(spec["module"]), str(spec["class_name"]))
        except Exception as exc:  # noqa: BLE001
            skipped[name] = str(exc)
            logger.warning("Skipping agent catalog registration for %s: %s", name, exc)
            continue

        AgentRegistry.register(
            name=name,
            agent_class=agent_class,
            capabilities=list(spec.get("capabilities", [])),
            description=str(spec.get("description", "")),
            cost_tier=str(spec.get("cost_tier", "medium")),
            category=str(spec.get("category", "")),
            tags=list(spec.get("tags", [])),
            status=str(spec.get("status", "healthy")),
            overwrite=True,
        )
        registered_names.append(name)

    result = {
        "registered_count": len(registered_names),
        "registered_names": sorted(registered_names),
        "skipped": skipped,
    }
    logger.info(
        "Agent catalog registration complete: %s registered, %s skipped",
        result["registered_count"],
        len(skipped),
    )
    return result
